# action.yaml
name: 'Create API docs Action'
description: 'Adds the API docs for a service to OpsLevel'
inputs:
  integration_url:
    description: 'The OpsLevel deploy integration url'
    required: true
    default: ''
  api_docs_location:
    description: 'The path to the API docs for a service'
    required: true
    default: ''
outputs:
  api_docs:
    description: 'The API docs for a service'
runs:
  using: 'docker'
  image: 'Dockerfile'
